export const QUERY_KEY = {
  SAMPLE: "sample",
  AUTH_USER: "auth-user",
  OWNER_USERS: "owner-users",
  OWNER_RESTAURANT: "owner-restaurant",
  OWNER_BRANCHES: "owner-branches",
  OWNER_BRANCH: "owner-branch",
  MANAGE_CATEGORIES: "manage-categories",
  MANAGE_CATEGORY: "manage-category",
  MANAGE_MENU_ITEMS: "manage-menu-items",
  MANAGE_MENU_ITEM: "manage-menu-item",
  MANAGE_PRICE_HISTORY: "manage-price-history",
  MANAGER_USERS: "manager-users",
  MY_BRANCHES: "my-branches",
  MY_BRANCH: "my-branch",
  MY_BRANCH_MENU: "my-branch-menu",
  MY_MENU_ITEM: "my-menu-item",
  PUBLIC_TABLE: "public-table",
  PUBLIC_SESSION_MENU: "public-session-menu",
  PUBLIC_BRANCH_CATEGORIES: "public-branch-categories",
};
